export default {
  1779: "https://upload.wikimedia.org/wikipedia/pt/b/b4/Corinthians_simbolo.png",
  1783: "https://upload.wikimedia.org/wikipedia/commons/9/93/Flamengo-RJ_%28BRA%29.png",
  1769: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Palmeiras_logo.svg/1024px-Palmeiras_logo.svg.png",
  6685: "https://upload.wikimedia.org/wikipedia/commons/9/92/LogoSantosFC.png",
  1776: "https://upload.wikimedia.org/wikipedia/pt/4/4b/S%C3%A3o_Paulo_Futebol_Clube.png",
  6684: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Escudo_do_Sport_Club_Internacional.svg/1024px-Escudo_do_Sport_Club_Internacional.svg.png",
  1777: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Escudo_EC_Bahia.png/800px-Escudo_EC_Bahia.png",
  1767: "https://upload.wikimedia.org/wikipedia/pt/a/a1/Gremio.png",
  1768: "https://upload.wikimedia.org/wikipedia/pt/c/c7/Club_Athletico_Paranaense_2019.png",
  4250: "https://upload.wikimedia.org/wikipedia/pt/3/38/GoiasEC2019.png",
  1766: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Atletico_mineiro_galo.png/800px-Atletico_mineiro_galo.png",
  1770: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Botafogo_de_Futebol_e_Regatas_logo.svg/800px-Botafogo_de_Futebol_e_Regatas_logo.svg.png",
  1780: "https://upload.wikimedia.org/wikipedia/pt/8/89/Club_de_Regatas_Vasco_da_Gama.png",
  3984: "https://upload.wikimedia.org/wikipedia/pt/5/5e/FortalezaEC2019.png",
  1765: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Fluminense_FC_escudo.png",
  1837: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cear%C3%A1_Sporting_Club_logo.svg/1024px-Cear%C3%A1_Sporting_Club_logo.svg.png",
  4244: "https://upload.wikimedia.org/wikipedia/pt/b/b2/CSAal.png",
  1771: "https://upload.wikimedia.org/wikipedia/pt/e/e4/Logo_oficial_do_Cruzeiro.png",
  1775: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Avai_FC_%2805-E%29_-_SC.svg/800px-Avai_FC_%2805-E%29_-_SC.svg.png",
  1772: "https://upload.wikimedia.org/wikipedia/pt/e/e4/Novo_escudo_da_Associa%C3%A7%C3%A3o_Chapecoense_de_Futebol.png"
};
